# Generated by Django 5.1.6 on 2025-03-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0005_category_user_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/products/'),
        ),
    ]
