# Generated by Django 5.1.6 on 2025-03-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0006_remove_item_imageurl_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='templates/uploads/products/'),
        ),
    ]
