# Generated by Django 5.1.7 on 2025-03-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0008_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='TeamIGS/Static/ItemPictures'),
        ),
    ]
