# Generated by Django 5.1.7 on 2025-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0011_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='TeamIGS/static/ItemPictures'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
