# Generated by Django 5.1.6 on 2025-04-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0016_alter_category_slug_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
