# Generated by Django 5.1.6 on 2025-04-10 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0020_rename_ordered_order_complete_remove_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeamIGS.item'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
