# Generated by Django 4.2.20 on 2025-04-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0020_rename_ordered_order_complete_remove_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
