# Generated by Django 5.1.7 on 2025-04-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0021_alter_orderitem_item_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
