# Generated by Django 5.1.6 on 2025-04-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0022_remove_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
