# Generated by Django 4.2.20 on 2025-04-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0021_alter_category_options'),
        ('TeamIGS', '0023_alter_category_options_remove_item_slug'),
    ]

    operations = [
    ]
