<<<<<<< HEAD
# Generated by Django 4.2.20 on 2025-04-17 23:13
=======
# Generated by Django 4.2.20 on 2025-04-17 23:06
>>>>>>> e5c7a667a73f27dcd634af98c0bf0087189dd3b9

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('TeamIGS', '0024_merge_20250417_1611'),
=======
        ('TeamIGS', '0024_merge_20250417_1604'),
>>>>>>> e5c7a667a73f27dcd634af98c0bf0087189dd3b9
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='dateOrdered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='transactionId',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
