# Generated by Django 4.2.20 on 2025-04-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamIGS', '0024_merge_20250417_1604'),
        ('TeamIGS', '0024_merge_20250417_1611'),
    ]

    operations = [
    ]
